### ISSUE TITLE
CSS fails to load when visiting https://urho3d.github.io 

### ISSUE THREAD

**Issue by Modanung** [urho3d/urho3d.github.io#6] opened 2015-04-02 20:42 UTC
Every time I visit urho3d.github.io Firefox blocks content with the notice: "This site does not supply identity information."
I need to disable this protection for every new session for the CSS to load. In this case I'm not held back by this, but I can imagine other people are.

**Comment by friesencr** [comment] 2015-04-02 21:09
Reproduced.  Thanks.

**Comment by Modanung** [comment] 2015-04-03 05:46
It only occurs on the default loaded main page, not on any on-site linked pages. This is also the only page being loaded through https.

**Comment by Modanung** [comment] 2015-04-03 07:45
Actually... it seems to be DuckDuckGo that prefixes https to urho3d.github.io links.

**Comment by friesencr** [comment] 2015-04-03 16:44
Thanks for the report.  We should have https support soon.  Our static site compiler was hardcoding links to http.  I didn't know that duckduckgo preferred https links.  I would suspect others will follow suit in time.

**Comment by Sleaker** [comment] 2015-12-07 07:00
This is still a problem, I use https everywhere and it causes the site to not load properly.

**Comment by weitjong** [comment] 2015-12-07 07:57
Thanks for reporting. Yes, this is still an **open** issue. You are advised to use ```http``` protocol when browsing this website at the moment.

**Comment by Sleaker** [comment] 2015-12-07 14:30
@weitjong - You guys just aren't using jekyll properly, you setup your basepath incorrectly. This is a very easy fix.: https://github.com/urho3d/urho3d.github.io/blob/master/_config.yml#L57 - Probably just need to update to the latest version of it as that config file looks very old/way different than the current ones I've looked through.

**Comment by weitjong** [comment] 2015-12-07 15:41
> You guys just aren't using jekyll properly, you setup your basepath incorrectly. This is a very easy fix.: https://github.com/urho3d/urho3d.github.io/blob/master/_config.yml#L57

That may be so. However, it is in my opinion that our **static** website does not need ```https``` protocol now, so I don't bother to fix it myself. But PR is welcome, but see the discussion on PR #7 before you do so.

> Probably just need to update to the latest version of it as that config file looks very old/way different than the current ones I've looked through.

It is true that we have not merged with any upstreams changes from Jekyll-Bootstrap, HTML5 boilerplate, etc in to the our code base. It was last done in the last website revamp exercise. We will probably only do such exercise once in a very long while. BTW, I am not surprised that our config looks different. It should be different because of our own customization.

**Comment by Sleaker** [comment] 2015-12-07 16:59
@weitjong - since you're hosting on github you can't turn https off, this is going to be a problem.  If you were self-hosting I'd say it was a non-issue. But more and more browsers are automatically going to the https site by default, and extensions such as https everywhere are becoming more prevalent to prevent ad-injection type stuffs.

**Closed** 2016-07-24 06:10 UTC
Labels: enhancement

**Comment by Modanung** [comment] 2016-07-24 19:43
Cool :)
