### ISSUE TITLE
Footer is over the header element

### ISSUE THREAD

**Issue by ArnisLielturks** [urho3d/urho3d.github.io#16] opened 2016-12-23 10:30 UTC
[https://s24.postimg.org/oh5y78f05/Untitled.png](https://s24.postimg.org/oh5y78f05/Untitled.png)

To fix it, the header DOM element should have the following CSS property added:
`top: 0`

and for the footer DOM element the CSS property "bottom" should be changed from
`bottom: 50px`
to
`bottom: 0`

**Comment by weitjong** [comment] 2016-12-23 10:51
Yes, it is getting a bit crowded down there, especially after the new logo replacement. However, I don't like your fix to alter the margin to make the space. Our current website design is based on http://orderedlist.com/minimal/. The footer could be moved away all together to other places instead. I actually have plan to revamp the website if I have time later. Thks for your report anyway.

**Comment by weitjong** [comment] 2016-12-23 15:11
Mark it as duplicate of #12.

**Closed by weitjong** 2016-12-23 15:11 UTC
Labels: duplicate
